project:
  type: website

website:
  title: "HTML Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: brand
    css: styles.css
    toc: true



