project:
  type: website

website:
  title: "HTML Example"
  navbar:
    left:
      - href: index.qmd
        text: Page 1
      - href: about.qmd
        text: Page 2

format:
  html:
    theme: brand
    css: styles.css
    toc: true



