- uses: a11ywatch/github-action@v2.1.10
  with:
    WEBSITE_URL: ${{ https://dhhs.utah.gov/health-dashboards/opioid-data/ }}
    SITE_WIDE: true
    SUBDOMAINS: true
    TLD: false
    SITEMAP: true
    FAIL_ERRORS_COUNT: 15
    LIST: true
    FIX: false
    UPGRADE: false

  env:
    DEFAULT_RUNNERS: htmlcs,axe
    PAGEMIND_IGNORE_WARNINGS: true
    AI_DISABLED: false
